server:
  port: 8081
---
spring:
  application:
    name: itq-number-generate-service
  data:
    mongodb:
      uri: ${SPRING_MONGODB_URI:mongodb://itq-user:itq-password@localhost:27017/itq-numbers-db?authSource=admin}
      auto-index-creation: true