server:
  port: 8081
---
spring:
  application:
    name: itq-number-generate-service
  data:
    mongodb:
      uri: ${SPRING_MONGODB_URI:mongodb://mongoadmin:mongoadminpassword@localhost:27017/itq-numbers-db?authSource=admin}
      auto-index-creation: true
      connection-timeout: 10000
      retry:
        enabled: true
  datasource:
    initialization-mode: always